# Generated by Django 4.1.7 on 2023-08-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0039_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(blank=True, verbose_name='price')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='cassette')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.condition', verbose_name='condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'default_related_name': 'whishlists',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(blank=True, verbose_name='price')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='cassette')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.condition', verbose_name='condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'default_related_name': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(blank=True, verbose_name='price')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='cassette')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.condition', verbose_name='condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'default_related_name': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(blank=True, verbose_name='price')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='cassette')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.condition', verbose_name='condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'default_related_name': 'collections',
            },
        ),
    ]
