# Generated by Django 4.1.7 on 2023-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'cassette', 'condition'), name='unique_cassette_in_collection'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('user', 'cassette'), name='unique_cassette_in_exchange'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('user', 'cassette'), name='unique_cassette_in_sale'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'cassette'), name='unique_cassette_in_wishlist'),
        ),
    ]
