# Generated by Django 4.1.7 on 2023-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
