# Generated by Django 4.1.7 on 2023-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0002_alter_collection_price_alter_exchange_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
