# Generated by Django 4.1.7 on 2023-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_management', '0003_alter_collection_price_alter_exchange_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'default_related_name': 'wishlists'},
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('user', 'cassette', 'condition'), name='unique_cassette_in_collection'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('user', 'cassette', 'condition'), name='unique_cassette_in_exchange'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('user', 'cassette', 'condition'), name='unique_cassette_in_sale'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'cassette', 'condition'), name='unique_cassette_in_wishlist'),
        ),
    ]
