# Generated by Django 4.1.7 on 2023-09-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_alter_condition_description'),
        ('collection_management', '0004_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.condition', verbose_name='condition'),
        ),
    ]
