# Generated by Django 4.1.7 on 2023-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_country_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=200, verbose_name='country'),
        ),
    ]
