# Generated by Django 4.1.7 on 2023-07-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_country_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
