# Generated by Django 4.1.7 on 2023-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_country_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='country',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='country'),
        ),
    ]
