# Generated by Django 4.1.7 on 2023-08-08 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_country_title_en_country_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating score')),
                ('is_published', models.BooleanField(default=True, verbose_name='publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_collectors', to=settings.AUTH_USER_MODEL, verbose_name='collector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ('-created',),
            },
        ),
    ]
