# Generated by Django 4.1.7 on 2023-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_collectorfeedback_unique_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorfeedback',
            name='feedback',
            field=models.TextField(default='gggg', verbose_name='feedback'),
            preserve_default=False,
        ),
    ]
