# Generated by Django 4.1.7 on 2023-10-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('title',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('title',), 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
    ]
