# Generated by Django 4.1.7 on 2023-10-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_country_options_alter_language_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200, verbose_name='system name')),
                ('admin_name', models.CharField(max_length=200, verbose_name='admin name')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'global text',
                'verbose_name_plural': 'global texts',
                'ordering': ('system_name',),
            },
        ),
    ]
