# Generated by Django 4.1.7 on 2023-05-02 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil', models.BooleanField(verbose_name='Coil')),
                ('slim_case', models.BooleanField(verbose_name='Slim case')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('condition', models.CharField(blank=True, choices=[('mint', 'Mint'), ('excellent', 'Excellent'), ('very_good', 'Very good'), ('good', 'Good'), ('poor', 'Poor')], max_length=50, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'Add cassettes',
                'verbose_name_plural': 'Cassettes',
            },
        ),
        migrations.CreateModel(
            name='CassetteTapeLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tape_length', models.IntegerField(verbose_name='Tape length')),
            ],
        ),
        migrations.CreateModel(
            name='CassetteYearRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='CassetteBrand',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteCollection',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteManufacturer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteSeries',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteTechnology',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassetteType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.basemodel')),
            ],
            bases=('catalog.basemodel',),
        ),
        migrations.CreateModel(
            name='CassettesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cassettes', verbose_name='Image')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette')),
            ],
            options={
                'verbose_name': 'Add image for cassette',
                'verbose_name_plural': 'Cassette images',
            },
        ),
        migrations.CreateModel(
            name='CassetteFrequencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='frequeryresponse')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette')),
            ],
            options={
                'verbose_name': 'Add frequency response for cassette',
                'verbose_name_plural': 'Cassette frequency responses',
            },
        ),
        migrations.CreateModel(
            name='CassetteBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='barcode')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette')),
            ],
            options={
                'verbose_name': 'Add barcode for cassette',
                'verbose_name_plural': 'Cassette barcodes',
            },
        ),
        migrations.AddField(
            model_name='cassette',
            name='tape_length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetapelength', verbose_name='Tape Length'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='year_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassetteyearrelease', verbose_name='Year Release'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettebrand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettecollection', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemanufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassetteseries', verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetechnology', verbose_name='Technology'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetype', verbose_name='Type'),
        ),
    ]
