# Generated by Django 4.1.7 on 2023-10-04 10:49

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('coil', models.BooleanField(blank=True, null=True, verbose_name='Coil')),
                ('slim_case', models.BooleanField(blank=True, null=True, verbose_name='Slim case')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('comment_en', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('comment_ru', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('year_release', models.IntegerField(blank=True, null=True, verbose_name='year Release')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date of comment created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date of comment updated')),
            ],
            options={
                'verbose_name': 'cassette',
                'verbose_name_plural': 'cassettes',
                'default_related_name': 'cassettes',
            },
        ),
        migrations.CreateModel(
            name='CassetteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='brands', verbose_name='image')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='CassetteChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Changer',
                'verbose_name_plural': 'Changers',
            },
        ),
        migrations.CreateModel(
            name='CassetteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='CassetteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of comment created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of comment updated')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CassetteManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='CassetteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='CassettePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poor', models.IntegerField(blank=True, null=True, verbose_name='Poor price')),
                ('good', models.IntegerField(blank=True, null=True, verbose_name='Good price')),
                ('very_good', models.IntegerField(blank=True, null=True, verbose_name='Very good price')),
                ('excellent', models.IntegerField(blank=True, null=True, verbose_name='Excellent price')),
                ('near_mint', models.IntegerField(blank=True, null=True, verbose_name='Near mint price')),
                ('mint', models.IntegerField(blank=True, null=True, verbose_name='Mint price')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='CassetteSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='CassetteTapeLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tape_length', models.CharField(max_length=32, verbose_name='tape length')),
            ],
            options={
                'verbose_name': 'tape length',
                'verbose_name_plural': 'tape lengtes',
            },
        ),
        migrations.CreateModel(
            name='CassetteTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='CassetteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, max_length=5, unique=True, verbose_name='abbreviation')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='description')),
                ('is_published', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.Image.image_path, verbose_name='image file')),
                ('view', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Front side of the package'), (2, 'Back side of the package'), (3, 'End side'), (4, 'Front side of the box'), (5, 'Back side of the box'), (6, 'Description 1'), (7, 'Description 2'), (8, 'Item (Side A)'), (9, 'Item (Side B)'), (10, 'General view (Box)'), (11, 'General view (Item)'), (12, 'General view'), (13, 'Barcode'), (14, 'Frequency response')], null=True, verbose_name='view')),
                ('is_cover', models.BooleanField(default=False, verbose_name='cover')),
                ('is_publish', models.BooleanField(default=True, verbose_name='publish')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.cassette', verbose_name='cassette')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ('cassette', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url/Slug')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of updated')),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='category')),
                ('logo', models.ImageField(blank=True, upload_to='category_logo')),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('is_published_to_home', models.BooleanField(default=False, verbose_name='Publish to home page')),
                ('brands', models.ManyToManyField(blank=True, related_name='categories', to='catalog.cassettebrand', verbose_name='Brands')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CassetteSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
