# Generated by Django 4.1.7 on 2023-10-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassetteseller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AddField(
            model_name='cassetteprice',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.cassette', verbose_name='cassette'),
        ),
        migrations.AddField(
            model_name='cassettemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettebrand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='cassettecomment',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.cassette', verbose_name='Cassette'),
        ),
        migrations.AddField(
            model_name='cassettecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cassettechanger',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette'),
        ),
        migrations.AddField(
            model_name='cassettechanger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changer'),
        ),
        migrations.AddField(
            model_name='cassettebrand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cassettes', to='catalog.cassettebrand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cassettes', to='catalog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_cassettes', to='core.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettemanufacturer', verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='markets',
            field=models.ManyToManyField(related_name='markets_cassettes', to='core.country', verbose_name='markets'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettemodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassetteseries', verbose_name='series'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='tape_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettetapelength', verbose_name='tape Length'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='tape_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettetype', verbose_name='tape type'),
        ),
        migrations.AddField(
            model_name='cassette',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cassettetechnology', verbose_name='technology'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_publish', True)), fields=('cassette', 'view'), name='unique_cassette_view', violation_error_message='Only one unique view per cassette can be published'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('cassette',), name='unique_cassette_cover', violation_error_message='Only one view per cassette per cassette can be set as cover'),
        ),
    ]
