# Generated by Django 4.1.7 on 2023-05-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CasseteCategory',
        ),
    ]
