# Generated by Django 4.1.7 on 2023-05-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_category_cassetecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CasseteCategory',
            new_name='CassetteCategory',
        ),
    ]
