# Generated by Django 4.1.7 on 2023-10-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cassettesort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettesort', verbose_name='sort'),
        ),
    ]
