# Generated by Django 4.1.7 on 2023-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_cassetecategory_cassettecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettecategory',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
