# Generated by Django 4.1.7 on 2023-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cassettecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassettecategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
