# Generated by Django 4.1.7 on 2023-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cassette_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettesort',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='cassettesort',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='title'),
        ),
    ]
