# Generated by Django 4.1.7 on 2023-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_cassettecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
