# Generated by Django 4.1.7 on 2023-10-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_country_options_alter_language_options'),
        ('catalog', '0007_alter_cassettebrand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='markets',
            field=models.ManyToManyField(null=True, related_name='markets_cassettes', to='core.country', verbose_name='markets'),
        ),
    ]
