# Generated by Django 4.1.7 on 2023-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_cassette_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='upload_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
