# Generated by Django 4.1.7 on 2023-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cassettecategory_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='year_release',
            field=models.CharField(max_length=4, verbose_name='Year Release'),
        ),
        migrations.AlterField(
            model_name='cassettecategory',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.cassettebrand', verbose_name='Brands'),
        ),
    ]
