# Generated by Django 4.1.7 on 2023-10-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cassette_upload_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteprice',
            name='cassette',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.cassette', verbose_name='cassette'),
        ),
    ]
