# Generated by Django 4.1.7 on 2023-10-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_cassetteprice_cassette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('type', 'title'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
