# Generated by Django 4.1.7 on 2023-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_cassette_year_release'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CassetteYearRelease',
        ),
    ]
