# Generated by Django 4.1.7 on 2023-05-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_country_title'),
        ('catalog', '0014_delete_cassetteyearrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettebrand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='Country'),
        ),
    ]
