# Generated by Django 4.1.7 on 2023-05-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_cassettebrand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettecategory', verbose_name='Category'),
        ),
    ]
