# Generated by Django 4.1.7 on 2023-05-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_cassette_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettebrand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='catalog.cassettebrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='catalog.cassettecategory', verbose_name='Category'),
        ),
    ]
