# Generated by Django 4.1.7 on 2023-05-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_cassette_condition_cassetteprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='catalog.cassettebrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='coil',
            field=models.BooleanField(blank=True, verbose_name='Coil'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettecollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassetteseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='slim_case',
            field=models.BooleanField(blank=True, verbose_name='Slim case'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='tape_length',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetapelength', verbose_name='Tape Length'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='technology',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetechnology', verbose_name='Technology'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='year_release',
            field=models.IntegerField(blank=True, verbose_name='Year Release'),
        ),
        migrations.AlterField(
            model_name='cassetteprice',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.cassette', verbose_name='cassette'),
        ),
    ]
