# Generated by Django 4.1.7 on 2023-05-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_cassetteseller_cassettechanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassetteprice',
            name='condition',
            field=models.CharField(choices=[('poor', 'Poor'), ('good', 'Good'), ('very_good', 'Very good'), ('excellent', 'Excellent'), ('nearmint', 'Near mint'), ('mint', 'Mint')], max_length=100, verbose_name='condition'),
        ),
    ]
