# Generated by Django 4.1.7 on 2023-05-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_cassetteprice_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassette',
            name='price',
        ),
    ]
