# Generated by Django 4.1.7 on 2023-05-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_remove_cassette_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='catalog.cassettebrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemanufacturer', verbose_name='Manufacturer'),
        ),
    ]
