# Generated by Django 4.1.7 on 2023-05-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_cassette_brand_alter_cassette_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='coil',
            field=models.BooleanField(blank=True, null=True, verbose_name='Coil'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettecollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemanufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassetteseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='slim_case',
            field=models.BooleanField(blank=True, null=True, verbose_name='Slim case'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='tape_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetapelength', verbose_name='Tape Length'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassettetechnology', verbose_name='Technology'),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='year_release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Release'),
        ),
    ]
