# Generated by Django 4.1.7 on 2023-06-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_cassette_coil_alter_cassette_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassettesimage',
            name='image',
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='box_back_side',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Back side of the box'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='box_front_side',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Front side of the box'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='box_general_view',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='General view (Box)'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='description_one',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Description 1'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='description_two',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='general_view',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='General view'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='item_general_view',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='General view (Item)'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='item_side_a',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Item (Side A)'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='item_side_b',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Item (Side B)'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='package_back_side',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Back side of the package'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='package_end_side',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='End side'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='package_front_side',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='Front side of the package'),
        ),
        migrations.AlterField(
            model_name='cassettesimage',
            name='cassette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette'),
        ),
    ]
