# Generated by Django 4.1.7 on 2023-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_cassettesimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassettefrequencyresponse',
            name='cassette',
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='General view'),
        ),
        migrations.AddField(
            model_name='cassettesimage',
            name='frequency_response',
            field=models.ImageField(blank=True, null=True, upload_to='cassettes', verbose_name='General view'),
        ),
        migrations.DeleteModel(
            name='CassetteBarcode',
        ),
        migrations.DeleteModel(
            name='CassetteFrequencyResponse',
        ),
    ]
