# Generated by Django 4.1.7 on 2023-06-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0029_remove_cassetteprice_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassetteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of comment created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date of comment updated')),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cassette', verbose_name='Cassette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cassette comment',
                'verbose_name_plural': 'Cassette comments',
            },
        ),
    ]
