# Generated by Django 4.1.7 on 2023-06-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0030_cassettecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassettecomment',
            name='cassette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.cassette', verbose_name='Cassette'),
        ),
        migrations.AlterField(
            model_name='cassettecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
