# Generated by Django 4.1.7 on 2023-06-30 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_cassettecomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of comment created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cassette',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of comment updated'),
        ),
    ]
