# Generated by Django 4.1.7 on 2023-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_cassette_created_cassette_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassettecomment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
    ]
