# Generated by Django 4.1.7 on 2023-07-04 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_cassettecomment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basemodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of updated'),
        ),
        migrations.AddField(
            model_name='cassettecategory',
            name='is_published_to_home',
            field=models.BooleanField(default=False, verbose_name='Publish to home page'),
        ),
        migrations.AddField(
            model_name='cassettecategory',
            name='type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=5),
        ),
    ]
