# Generated by Django 4.1.7 on 2023-07-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_country_title'),
        ('catalog', '0035_basemodel_created_basemodel_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cassette',
            options={'verbose_name': 'Cassette', 'verbose_name_plural': 'Cassettes'},
        ),
        migrations.AlterModelOptions(
            name='cassettebrand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='cassettecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cassettechanger',
            options={'verbose_name': 'Changer', 'verbose_name_plural': 'Changers'},
        ),
        migrations.AlterModelOptions(
            name='cassettecollection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='cassettecomment',
            options={'ordering': ('-created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='cassettemanufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='cassettemodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='cassetteprice',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='cassetteseller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelOptions(
            name='cassetteseries',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='cassettesimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='cassettetapelength',
            options={'verbose_name': 'Tape length', 'verbose_name_plural': 'Tape lengtes'},
        ),
        migrations.AlterModelOptions(
            name='cassettetechnology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelOptions(
            name='cassettetype',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Url/Slug'),
        ),
        migrations.AlterField(
            model_name='cassettebrand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='country'),
        ),
    ]
