# Generated by Django 4.1.7 on 2023-07-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_basemodel_title_en_basemodel_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cassettebrand',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
    ]
