# Generated by Django 4.1.7 on 2023-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_cassettebrand_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, max_length=3, unique=True, verbose_name='abbreviation')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_published', models.BooleanField(default=False, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
    ]
