# Generated by Django 4.1.7 on 2023-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
