# Generated by Django 4.1.7 on 2023-08-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_condition_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(blank=True, max_length=5000, verbose_name='description'),
        ),
    ]
